services:
  razgalev-admin:
    image: pkg-starter-kit
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
      args:
        CODE_PATH_HOST: ${CODE_PATH_HOST:-.}
        CODE_PATH_CONTAINER: ${CODE_PATH_CONTAINER:-/app}
    restart: always
    volumes:  
      - ${CODE_PATH_HOST:-.}:${CODE_PATH_CONTAINER:-/app}
